// <auto-generated />
using System;
using BookStoreShop.Models.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101161712_AddSeedUser")]
    partial class AddSeedUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreShop.Models.Domain.Entities.BookAgg.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedAtFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PublishYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Asghar Farhadi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(5868),
                            ImagePath = "/img/books/seller.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Seller"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Soroush Sehat",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(5888),
                            ImagePath = "/img/books/zarrafeh.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Breakfast with "
                        },
                        new
                        {
                            Id = 3,
                            Author = "Asghar Farhadi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(5891),
                            ImagePath = "/img/books/hero.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Hero"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Saead Roustaiee",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(5893),
                            ImagePath = "/img/books/metri.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Metri Shish o nim"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Asghar Farhadi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(5952),
                            ImagePath = "/img/books/hotel.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Hotel"
                        });
                });

            modelBuilder.Entity("BookStoreShop.Models.Domain.Entities.CategoryAgg.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Biography",
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(8068),
                            Description = "Bio",
                            ImagePath = "/img/category/bio.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Comedy",
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(8074),
                            Description = "Comedy",
                            ImagePath = "/img/category/comedy.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Political",
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(8076),
                            Description = "Political",
                            ImagePath = "/img/category/political.jpeg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Sport",
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(8078),
                            Description = "Sport",
                            ImagePath = "/img/category/sport.jpeg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Tragedi",
                            CreatedAt = new DateTime(2025, 11, 1, 19, 47, 11, 676, DateTimeKind.Local).AddTicks(8079),
                            Description = "Tragedi",
                            ImagePath = "/img/category/tragedi.jpeg"
                        });
                });

            modelBuilder.Entity("BookStoreShop.Models.Domain.Entities.UserAgg.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "admin",
                            Password = "123",
                            Role = 1,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("BookStoreShop.Models.Domain.Entities.BookAgg.Book", b =>
                {
                    b.HasOne("BookStoreShop.Models.Domain.Entities.CategoryAgg.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookStoreShop.Models.Domain.Entities.CategoryAgg.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
