// <auto-generated />
using System;
using BookStoreShop.Models.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreShop.Models.Domain.Entities.BookAgg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedAtFA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PublishYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Asghar Farhadi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(3124),
                            ImagePath = "/img/books/seller.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Seller"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Soroush Sehat",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(3149),
                            ImagePath = "/img/books/zarrafeh.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Breakfast with "
                        },
                        new
                        {
                            Id = 3,
                            Author = "Asghar Farhadi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(3152),
                            ImagePath = "/img/books/hero.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Hero"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Saead Roustaiee",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(3156),
                            ImagePath = "/img/books/metri.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Metri Shish o nim"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Asghar Farhadi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(3158),
                            ImagePath = "/img/books/hotel.jpeg",
                            PageCount = 200,
                            Price = 200000m,
                            PublishYear = "1398",
                            Title = "Hotel"
                        });
                });

            modelBuilder.Entity("BookStoreShop.Models.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Biography",
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(5542),
                            Description = "Bio",
                            ImagePath = "/img/category/bio.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Comedy",
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(5552),
                            Description = "Comedy",
                            ImagePath = "/img/category/comedy.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Political",
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(5555),
                            Description = "Political",
                            ImagePath = "/img/category/political.jpeg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Sport",
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(5557),
                            Description = "Sport",
                            ImagePath = "/img/category/sport.jpeg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Tragedi",
                            CreatedAt = new DateTime(2025, 10, 28, 23, 28, 49, 212, DateTimeKind.Local).AddTicks(5558),
                            Description = "Tragedi",
                            ImagePath = "/img/category/tragedi.jpeg"
                        });
                });

            modelBuilder.Entity("BookStoreShop.Models.Domain.Entities.BookAgg", b =>
                {
                    b.HasOne("BookStoreShop.Models.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookStoreShop.Models.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
